### ISSUE TITLE
[question] Elasticsearch version not supported by Graylog

### ISSUE THREAD

**Issue by ppferrari** [KongZ/charts#110]
Hello 👋🏻 

The latest `elasticsearch` version installed by this chart is not supported by `graylog` 4.x as described [here](https://docs.graylog.org/v1/docs/elasticsearch). Should this helm use the elasticsearch version supported by graylog (I think is [7.10.2](https://artifacthub.io/packages/helm/elastic/elasticsearch/7.10.2))?

Thank you in advance,
Pietro

**Comment by jceb** [comment]
I had no issues running the previous version of elasticsearch with graylog .. this downgrade unfortunately breaks elasticsearch.

**Comment by KongZ** [comment]
@jceb can you post more detail what errors you found? 

Setting default to 7.10.2 is recommended version by Graylog (licensing issue). The helm-chart users are freely to set a new version if users do not have issue with the license.

**Comment by jceb** [comment]
I had rolled out a version of the chart that installs a higher version of elasticsearch. After installing the current version the elasticsearch pod wouldn't change into running state complaining that the existing database is not compatible with the current version. 

The solution for the issue is apparently to recreate the indices. I didn't want to do that and stopped the investigation here.

Is there a way to say the elasticsearch version so I can avoid reindexing, e.g. through values.yaml?

**Comment by KongZ** [comment]
You can't downgrade Elasticsearch. The Elasticsearch can only go forward.
I would suggest you to specify the Elasticsearch version in `values.yaml` then upgrade the release.

**Comment by jceb** [comment]
Which property do I have to set in values.yaml to specify the elasticsearch version?

**Comment by KongZ** [comment]
The easiest way is set the dependency here https://github.com/KongZ/charts/blob/main/charts/graylog/Chart.yaml#L20
Alternatively, set `elasticsearch.imageTag`. Checkout elasticsearch documentation here https://github.com/elastic/helm-charts/tree/main/elasticsearch
