### ISSUE TITLE
setup - chown /usr/share/graylog/data Operation not permitted

### ISSUE THREAD

**Issue by oblak-be** [KongZ/charts#158]
**Describe the bug**

Since the newest chart release 2.3.6, my graylog-server pod doesn't start anymore because the initcontainer fails with the error,  `chown /usr/share/graylog/data Operation not permitted`.

I think it might have to do with the securityContext that was enforced.

When I downgrade my chart to 2.3.5 , there is no issue, and the servers starts successfully.

**Version of Helm and Kubernetes**:

Helm Version: v3.11
Kubernetes Version: v1.21 :scream: 

**Which version of the chart**: 2.3.6

**Comment by KongZ** [comment]
You can set `graylog.podSecurityContext` to `{}` when upgrading. 
It will override the new default value.

**Comment by andrewjmurphy** [comment]
I faced this issue as well and the above workaround did not work for me.
`graylog.podSecurityContext` sets the securityContext at the pod level, not within the init container, which was what was causing the problem.

Furthermore if helm encounters a dictionary that is overridden by another dictionary it will merge the two, not replace one with the other. Merging a dictionary with `{}` is a no-op, so setting it as above had no effect.

In order to prevent the securityContext being set in the init container I had to set `graylog.securityContext` to `false`

**Comment by Argalep** [comment]
I have the same problem. Helm chart version 2.3.6 has the same problem.  

> '/k8s/kubectl' saved
> chown: /usr/share/graylog/data/journal: Operation not permitted
> chown: /usr/share/graylog/data/journal: Operation not permitted
> chown: /usr/share/graylog/data/: Operation not permitted
> chown: /usr/share/graylog/data/: Operation not permitted

**Comment by luizjr** [comment]
I had the same problem.
This solution of @andrewjmurphy  worked: `graylog.securityContext` to `false`

But how are we going to proceed, @KongZ ... can I put this value in helm, or is there another way to solve it?
